// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Primary design header
//
// This header should be included by all source files instantiating the design.
// The class here is then constructed to instantiate the design.
// See the Verilator manual for examples.

#ifndef VERILATED_VM_TOPSIM_H_
#define VERILATED_VM_TOPSIM_H_  // guard

#include "verilated_heavy.h"

//==========

class Vm_topsim__Syms;

//----------

VL_MODULE(Vm_topsim) {
  public:
    
    // PORTS
    // The application code writes and reads these signals to
    // propagate new values into/out from the Verilated model.
    VL_IN8(CLK,0,0);
    VL_IN8(RST_X,0,0);
    
    // LOCAL SIGNALS
    // Internals; generally not touched by application code
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ m_topsim__DOT__CLK;
        CData/*0:0*/ m_topsim__DOT__RST_X;
        CData/*0:0*/ m_topsim__DOT__w_halt;
        CData/*0:0*/ m_topsim__DOT__w_finish;
        CData/*0:0*/ m_topsim__DOT__w_data_we;
        CData/*2:0*/ m_topsim__DOT__w_data_ctrl;
        CData/*0:0*/ m_topsim__DOT__w_clint_we;
        CData/*0:0*/ m_topsim__DOT__w_plic_we;
        CData/*0:0*/ m_topsim__DOT__w_busy;
        CData/*1:0*/ m_topsim__DOT__w_tlb_req;
        CData/*0:0*/ m_topsim__DOT__w_tlb_flush;
        CData/*0:0*/ m_topsim__DOT__w_txd;
        CData/*0:0*/ m_topsim__DOT__w_rxd;
        CData/*0:0*/ m_topsim__DOT__w_init_done;
        CData/*0:0*/ m_topsim__DOT__w_init_stage;
        CData/*0:0*/ m_topsim__DOT__CORE_RST_X;
        CData/*1:0*/ m_topsim__DOT__ddr2_dqs_n;
        CData/*1:0*/ m_topsim__DOT__ddr2_dqs_p;
        CData/*2:0*/ m_topsim__DOT__ddr2_ba;
        CData/*0:0*/ m_topsim__DOT__ddr2_ras_n;
        CData/*0:0*/ m_topsim__DOT__ddr2_cas_n;
        CData/*0:0*/ m_topsim__DOT__ddr2_we_n;
        CData/*0:0*/ m_topsim__DOT__ddr2_ck_p;
        CData/*0:0*/ m_topsim__DOT__ddr2_ck_n;
        CData/*0:0*/ m_topsim__DOT__ddr2_cke;
        CData/*0:0*/ m_topsim__DOT__ddr2_cs_n;
        CData/*1:0*/ m_topsim__DOT__ddr2_dm;
        CData/*0:0*/ m_topsim__DOT__ddr2_odt;
        CData/*7:0*/ m_topsim__DOT__w_uart_data;
        CData/*0:0*/ m_topsim__DOT__w_uart_we;
        CData/*0:0*/ m_topsim__DOT__r_uart_busy;
        CData/*3:0*/ m_topsim__DOT__r_uart_count;
        CData/*3:0*/ m_topsim__DOT__r_uart_cycle;
        CData/*7:0*/ m_topsim__DOT__r_uart_data;
        CData/*0:0*/ m_topsim__DOT__r_finish;
        CData/*0:0*/ m_topsim__DOT__init_txd;
        CData/*0:0*/ m_topsim__DOT__tx_ready;
        CData/*7:0*/ m_topsim__DOT__uartdata;
        CData/*0:0*/ m_topsim__DOT__uartwe;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__CLK;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__RST_X;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__w_data_we;
        CData/*2:0*/ m_topsim__DOT__mmu__DOT__w_data_ctrl;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__r_finish;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__w_clint_we;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__w_plic_we;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__w_proc_busy;
        CData/*1:0*/ m_topsim__DOT__mmu__DOT__w_tlb_req;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__w_tlb_flush;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__w_txd;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__w_rxd;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__w_init_done;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__mig_clk;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__mig_rst_x;
        CData/*1:0*/ m_topsim__DOT__mmu__DOT__ddr2_dqs_n;
        CData/*1:0*/ m_topsim__DOT__mmu__DOT__ddr2_dqs_p;
        CData/*2:0*/ m_topsim__DOT__mmu__DOT__ddr2_ba;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__ddr2_ras_n;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__ddr2_cas_n;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__ddr2_we_n;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__ddr2_ck_p;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__ddr2_ck_n;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__ddr2_cke;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__ddr2_cs_n;
    };
    struct {
        CData/*1:0*/ m_topsim__DOT__mmu__DOT__ddr2_dm;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__ddr2_odt;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__o_clk;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__o_rst_x;
        CData/*7:0*/ m_topsim__DOT__mmu__DOT__w_uart_data;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__w_uart_we;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__w_init_stage;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__w_debug_btnd;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__page_walk_fail;
        CData/*2:0*/ m_topsim__DOT__mmu__DOT__r_pw_state;
        CData/*3:0*/ m_topsim__DOT__mmu__DOT__r_dev;
        CData/*3:0*/ m_topsim__DOT__mmu__DOT__r_virt;
        CData/*1:0*/ m_topsim__DOT__mmu__DOT__r_mc_mode;
        CData/*3:0*/ m_topsim__DOT__mmu__DOT__r_consf_head;
        CData/*3:0*/ m_topsim__DOT__mmu__DOT__r_consf_tail;
        CData/*4:0*/ m_topsim__DOT__mmu__DOT__r_consf_cnts;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__r_consf_en;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__w_tlb_busy;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__w_dram_busy;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__w_mc_we;
        CData/*2:0*/ m_topsim__DOT__mmu__DOT__w_mc_ctrl;
        CData/*1:0*/ m_topsim__DOT__mmu__DOT__w_mc_aces;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__w_mem_we;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__w_iscode;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__w_isread;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__w_iswrite;
        CData/*2:0*/ m_topsim__DOT__mmu__DOT__L1_xwr;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__L1_write;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__L1_success;
        CData/*2:0*/ m_topsim__DOT__mmu__DOT__L0_xwr;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__L0_write;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__L0_success;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__w_pte_we;
        CData/*2:0*/ m_topsim__DOT__mmu__DOT__r_tlb_use;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__w_tlb_inst_r_oe;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__w_tlb_data_r_oe;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__w_tlb_data_w_oe;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__w_use_tlb;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__w_tlb_hit;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__w_tlb_inst_r_we;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__w_tlb_data_r_we;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__w_tlb_data_w_we;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__r_tlb_acs;
        CData/*2:0*/ m_topsim__DOT__mmu__DOT__w_mem_ctrl;
        CData/*3:0*/ m_topsim__DOT__mmu__DOT__w_dev;
        CData/*3:0*/ m_topsim__DOT__mmu__DOT__w_virt;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__w_dram_we;
        CData/*2:0*/ m_topsim__DOT__mmu__DOT__w_dram_ctrl;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__w_dram_aces;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__w_dram_le;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__w_cons_we;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__w_cons_req;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__w_disk_we;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__w_disk_req;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__w_imag_we;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__w_key_we;
        CData/*7:0*/ m_topsim__DOT__mmu__DOT__w_key_data;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__w_key_req;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__r_key_we;
        CData/*7:0*/ m_topsim__DOT__mmu__DOT__r_key_data;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__w_cons_irq_oe;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__w_disk_irq_oe;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__w_isdisk;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__w_virt_irq_oe;
    };
    struct {
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__w_plic_aces;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__r_plic_we;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__r_virt_irq_oe_t;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__r_plic_aces_t;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__w_mc_busy;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__w_tx_ready;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__r_uart_we;
        CData/*7:0*/ m_topsim__DOT__mmu__DOT__r_uart_data;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__w_cons_txd;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__w_pl_init_we;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__w_pl_init_done;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__w_debug_txd;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__w_rec_done;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__r_bbl_done;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__r_disk_done;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__r_dtree_done;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__w_zero_we;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__r_zero_we;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__r_zero_done;
        CData/*2:0*/ m_topsim__DOT__mmu__DOT__r_init_state;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__calib_done;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__w_dram_we_t;
        CData/*2:0*/ m_topsim__DOT__mmu__DOT__w_dram_ctrl_t;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__TLB_inst_r__DOT__CLK;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__TLB_inst_r__DOT__RST_X;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__TLB_inst_r__DOT__w_flush;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__TLB_inst_r__DOT__w_we;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__TLB_inst_r__DOT__w_oe;
        CData/*3:0*/ m_topsim__DOT__mmu__DOT__TLB_inst_r__DOT__r_valid;
        CData/*1:0*/ m_topsim__DOT__mmu__DOT__TLB_inst_r__DOT__w_ridx;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__TLB_inst_r__DOT__w_tagmatch;
        CData/*1:0*/ m_topsim__DOT__mmu__DOT__TLB_inst_r__DOT__w_widx;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__TLB_data_r__DOT__CLK;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__TLB_data_r__DOT__RST_X;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__TLB_data_r__DOT__w_flush;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__TLB_data_r__DOT__w_we;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__TLB_data_r__DOT__w_oe;
        CData/*3:0*/ m_topsim__DOT__mmu__DOT__TLB_data_r__DOT__r_valid;
        CData/*1:0*/ m_topsim__DOT__mmu__DOT__TLB_data_r__DOT__w_ridx;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__TLB_data_r__DOT__w_tagmatch;
        CData/*1:0*/ m_topsim__DOT__mmu__DOT__TLB_data_r__DOT__w_widx;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__TLB_data_w__DOT__CLK;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__TLB_data_w__DOT__RST_X;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__TLB_data_w__DOT__w_flush;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__TLB_data_w__DOT__w_we;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__TLB_data_w__DOT__w_oe;
        CData/*3:0*/ m_topsim__DOT__mmu__DOT__TLB_data_w__DOT__r_valid;
        CData/*1:0*/ m_topsim__DOT__mmu__DOT__TLB_data_w__DOT__w_ridx;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__TLB_data_w__DOT__w_tagmatch;
        CData/*1:0*/ m_topsim__DOT__mmu__DOT__TLB_data_w__DOT__w_widx;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__CLK;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__RST_X;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__w_stall;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__w_mic_mmuwe;
        CData/*2:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__w_mic_ctrl;
        CData/*1:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__w_mic_req;
        CData/*1:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__r_state;
        CData/*6:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__r_opcode;
        CData/*2:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__r_funct3;
        CData/*6:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__r_funct7;
        CData/*4:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__r_rd;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__w_we;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__w_reg_we;
        CData/*6:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__w_op;
    };
    struct {
        CData/*4:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__w_rd;
        CData/*4:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__w_rs1;
        CData/*4:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__w_rs2;
        CData/*2:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__w_funct3;
        CData/*6:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__w_funct7;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__w_reg_w;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__w_alu_b_rslt;
        CData/*6:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__w_alu_fn7;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__r_tkn;
        CData/*2:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__r_ctrl;
        CData/*1:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__r_addr2;
        CData/*3:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__w_we_sb;
        CData/*3:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__w_we_sh;
        CData/*3:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__w_we_sw;
        CData/*3:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__w_mic_lcmwe;
        CData/*6:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__imm_gen0__DOT__opcode;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__regs__DOT__CLK;
        CData/*4:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__regs__DOT__w_rs1;
        CData/*4:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__regs__DOT__w_rs2;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__regs__DOT__w_we;
        CData/*4:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__regs__DOT__rd;
        CData/*2:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__ALU_I__DOT__w_funct3;
        CData/*6:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__ALU_I__DOT__w_funct7;
        CData/*4:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__ALU_I__DOT__w_shamt;
        CData/*2:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__ALU_B__DOT__w_funct3;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__ALU_B__DOT__r_rslt;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__lm_mc__DOT__CLK;
        CData/*3:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__lm_mc__DOT__w_we;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__console__DOT__CLK;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__console__DOT__RST_X;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__console__DOT__w_we;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__console__DOT__w_oeirq;
        CData/*1:0*/ m_topsim__DOT__mmu__DOT__console__DOT__w_mode;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__console__DOT__w_req;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__console__DOT__w_keyreq;
        CData/*7:0*/ m_topsim__DOT__mmu__DOT__console__DOT__w_addr;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__disk__DOT__CLK;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__disk__DOT__RST_X;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__disk__DOT__w_we;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__disk__DOT__w_oeirq;
        CData/*1:0*/ m_topsim__DOT__mmu__DOT__disk__DOT__w_mode;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__disk__DOT__w_req;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__UartTx0__DOT__CLK;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__UartTx0__DOT__RST_X;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__UartTx0__DOT__WE;
        CData/*7:0*/ m_topsim__DOT__mmu__DOT__UartTx0__DOT__DATA;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__UartTx0__DOT__TXD;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__UartTx0__DOT__READY;
        CData/*3:0*/ m_topsim__DOT__mmu__DOT__UartTx0__DOT__cnt;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__ploader__DOT__CLK;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__ploader__DOT__RST_X;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__ploader__DOT__RXD;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__ploader__DOT__WE;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__ploader__DOT__DONE;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__ploader__DOT__KEY_WE;
        CData/*7:0*/ m_topsim__DOT__mmu__DOT__ploader__DOT__KEY_DATA;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__ploader__DOT__SER_EN;
        CData/*7:0*/ m_topsim__DOT__mmu__DOT__ploader__DOT__SER_DATA;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__ploader__DOT__serc__DOT__CLK;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__ploader__DOT__serc__DOT__RST_X;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__ploader__DOT__serc__DOT__RXD;
        CData/*7:0*/ m_topsim__DOT__mmu__DOT__ploader__DOT__serc__DOT__DATA;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__ploader__DOT__serc__DOT__EN;
        CData/*3:0*/ m_topsim__DOT__mmu__DOT__ploader__DOT__serc__DOT__stage;
    };
    struct {
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__debug_KEY__DOT__CLK;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__debug_KEY__DOT__RST_X;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__debug_KEY__DOT__w_btn;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__debug_KEY__DOT__w_txd;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__debug_KEY__DOT__w_key_we;
        CData/*7:0*/ m_topsim__DOT__mmu__DOT__debug_KEY__DOT__w_key_data;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__debug_KEY__DOT__w_rec_done;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__debug_KEY__DOT__r_uartwe;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__debug_KEY__DOT__r_rec_done;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__debug_KEY__DOT__w_tx_ready;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__debug_KEY__DOT__w_busy;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__debug_KEY__DOT__UartTx0__DOT__CLK;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__debug_KEY__DOT__UartTx0__DOT__RST_X;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__debug_KEY__DOT__UartTx0__DOT__w_we;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__debug_KEY__DOT__UartTx0__DOT__r_txd;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__debug_KEY__DOT__UartTx0__DOT__r_ready;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__debug_KEY__DOT__UartTx0__DOT__r_we;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__CLK;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__w_we;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__w_le;
        CData/*2:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__w_ctrl;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__w_stall;
        CData/*1:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__r_cache_state;
        CData/*2:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__r_ctrl;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__e_test;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__w_dram_stall;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__w_dram_le;
        CData/*2:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__w_dram_ctrl;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__w_cache_oe;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__w_cache_clr;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__w_cache_we;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__cache__DOT__CLK;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__cache__DOT__RST_X;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__cache__DOT__w_flush;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__cache__DOT__w_we;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__cache__DOT__w_clr;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__cache__DOT__w_oe;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__cache__DOT__w_mwe;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__cache__DOT__w_mvalid;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__cache__DOT__mem__DOT__CLK;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__cache__DOT__mem__DOT__w_we;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__idbmem__DOT__CLK;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__idbmem__DOT__w_we;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__idbmem__DOT__w_le;
        CData/*2:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__idbmem__DOT__w_ctrl;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__idbmem__DOT__w_stall;
        CData/*2:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__idbmem__DOT__r_ctrl;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__idbmem__DOT__r_le;
        CData/*2:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__idbmem__DOT__w_mctrl;
        CData/*7:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__idbmem__DOT__w_data1;
        CData/*7:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__idbmem__DOT__w_data2;
        CData/*7:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__idbmem__DOT__w_data3;
        CData/*7:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__idbmem__DOT__w_data4;
        CData/*7:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__idbmem__DOT__o_data1;
        CData/*7:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__idbmem__DOT__o_data2;
        CData/*7:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__idbmem__DOT__o_data3;
        CData/*7:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__idbmem__DOT__o_data4;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__idbmem__DOT__WE1;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__idbmem__DOT__WE2;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__idbmem__DOT__WE3;
        CData/*0:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__idbmem__DOT__WE4;
        CData/*0:0*/ m_topsim__DOT__p__DOT__CLK;
        CData/*0:0*/ m_topsim__DOT__p__DOT__RST_X;
        CData/*0:0*/ m_topsim__DOT__p__DOT__w_stall;
    };
    struct {
        CData/*0:0*/ m_topsim__DOT__p__DOT__w_clint_we;
        CData/*0:0*/ m_topsim__DOT__p__DOT__w_plic_we;
        CData/*0:0*/ m_topsim__DOT__p__DOT__w_busy;
        CData/*0:0*/ m_topsim__DOT__p__DOT__r_halt;
        CData/*2:0*/ m_topsim__DOT__p__DOT__w_data_ctrl;
        CData/*0:0*/ m_topsim__DOT__p__DOT__w_init_stage;
        CData/*1:0*/ m_topsim__DOT__p__DOT__w_tlb_req;
        CData/*0:0*/ m_topsim__DOT__p__DOT__w_data_we;
        CData/*0:0*/ m_topsim__DOT__p__DOT__w_tlb_flush;
        CData/*3:0*/ m_topsim__DOT__p__DOT__state;
        CData/*0:0*/ m_topsim__DOT__p__DOT__reserved;
        CData/*1:0*/ m_topsim__DOT__p__DOT__priv;
        CData/*0:0*/ m_topsim__DOT__p__DOT__r_cinsn;
        CData/*0:0*/ m_topsim__DOT__p__DOT__r_ir16_v;
        CData/*6:0*/ m_topsim__DOT__p__DOT__r_opcode;
        CData/*4:0*/ m_topsim__DOT__p__DOT__r_rd;
        CData/*4:0*/ m_topsim__DOT__p__DOT__r_rs1;
        CData/*4:0*/ m_topsim__DOT__p__DOT__r_rs2;
        CData/*2:0*/ m_topsim__DOT__p__DOT__r_funct3;
        CData/*4:0*/ m_topsim__DOT__p__DOT__r_funct5;
        CData/*6:0*/ m_topsim__DOT__p__DOT__r_funct7;
        CData/*0:0*/ m_topsim__DOT__p__DOT__r_op_AMO_SC;
        CData/*0:0*/ m_topsim__DOT__p__DOT__r_op_AMO_LR;
        CData/*0:0*/ m_topsim__DOT__p__DOT__r_op_LOAD;
        CData/*0:0*/ m_topsim__DOT__p__DOT__r_op_STORE;
        CData/*0:0*/ m_topsim__DOT__p__DOT__r_op_AMO;
        CData/*0:0*/ m_topsim__DOT__p__DOT__r_op_SYS;
        CData/*0:0*/ m_topsim__DOT__p__DOT__r_op_ECALL;
        CData/*0:0*/ m_topsim__DOT__p__DOT__r_op_SRET;
        CData/*0:0*/ m_topsim__DOT__p__DOT__r_op_MRET;
        CData/*0:0*/ m_topsim__DOT__p__DOT__r_op_CSR_MSTA;
        CData/*0:0*/ m_topsim__DOT__p__DOT__r_op_CSR_SSTA;
        CData/*6:0*/ m_topsim__DOT__p__DOT__r_alu_f7;
        CData/*0:0*/ m_topsim__DOT__p__DOT__r_tkn;
        CData/*0:0*/ m_topsim__DOT__p__DOT__r_if_done;
        CData/*1:0*/ m_topsim__DOT__p__DOT__r_if_state;
        CData/*0:0*/ m_topsim__DOT__p__DOT__w_wb_r_enable;
        CData/*3:0*/ m_topsim__DOT__p__DOT__w_state;
        CData/*0:0*/ m_topsim__DOT__p__DOT__r_init_stage;
        CData/*0:0*/ m_topsim__DOT__p__DOT__w_nalign4;
        CData/*0:0*/ m_topsim__DOT__p__DOT__w_usestate;
        CData/*1:0*/ m_topsim__DOT__p__DOT__w_if_state;
        CData/*0:0*/ m_topsim__DOT__p__DOT__w_cinsn;
        CData/*0:0*/ m_topsim__DOT__p__DOT__w_nop;
        CData/*4:0*/ m_topsim__DOT__p__DOT__w_rs1;
        CData/*4:0*/ m_topsim__DOT__p__DOT__w_rs2;
        CData/*0:0*/ m_topsim__DOT__p__DOT__w_regfile_we;
        CData/*0:0*/ m_topsim__DOT__p__DOT__w_op_priv;
        CData/*0:0*/ m_topsim__DOT__p__DOT__w_op_csr;
        CData/*0:0*/ m_topsim__DOT__p__DOT__w_alu_b_rslt;
        CData/*0:0*/ m_topsim__DOT__p__DOT__w_ex1;
        CData/*0:0*/ m_topsim__DOT__p__DOT__w_ex1_busy;
        CData/*2:0*/ m_topsim__DOT__p__DOT__r_data_ctrl;
        CData/*1:0*/ m_topsim__DOT__p__DOT__r_priv_t;
        CData/*0:0*/ m_topsim__DOT__p__DOT__w_csr_we;
        CData/*0:0*/ m_topsim__DOT__p__DOT__r_tlb_flush;
        CData/*0:0*/ m_topsim__DOT__p__DOT__w_com;
        CData/*2:0*/ m_topsim__DOT__p__DOT__r_com;
        CData/*0:0*/ m_topsim__DOT__p__DOT__w_d_we_t;
        CData/*0:0*/ m_topsim__DOT__p__DOT__w_d_en_t;
        CData/*0:0*/ m_topsim__DOT__p__DOT__r_data_we;
        CData/*0:0*/ m_topsim__DOT__p__DOT__r_data_en;
        CData/*2:0*/ m_topsim__DOT__p__DOT__r_tlb_req;
        CData/*4:0*/ m_topsim__DOT__p__DOT__decomp0__DOT__w_c0_rs1;
    };
    struct {
        CData/*4:0*/ m_topsim__DOT__p__DOT__decomp0__DOT__w_c0_rs2;
        CData/*4:0*/ m_topsim__DOT__p__DOT__decomp0__DOT__w_c0_rd;
        CData/*1:0*/ m_topsim__DOT__p__DOT__decomp0__DOT__w_c1_funct1;
        CData/*2:0*/ m_topsim__DOT__p__DOT__decomp0__DOT__w_c1_funct2;
        CData/*4:0*/ m_topsim__DOT__p__DOT__decomp0__DOT__w_c1_rs1;
        CData/*4:0*/ m_topsim__DOT__p__DOT__decomp0__DOT__w_c1_rs2;
        CData/*4:0*/ m_topsim__DOT__p__DOT__decomp0__DOT__w_c1_rd;
        CData/*4:0*/ m_topsim__DOT__p__DOT__decomp0__DOT__w_c1_shamt;
        CData/*4:0*/ m_topsim__DOT__p__DOT__decomp0__DOT__w_c2_rs2;
        CData/*4:0*/ m_topsim__DOT__p__DOT__decomp0__DOT__w_c2_rd;
        CData/*4:0*/ m_topsim__DOT__p__DOT__decomp0__DOT__w_c2_shamt;
        CData/*6:0*/ m_topsim__DOT__p__DOT__imm_gen0__DOT__opcode;
        CData/*0:0*/ m_topsim__DOT__p__DOT__regs__DOT__CLK;
        CData/*4:0*/ m_topsim__DOT__p__DOT__regs__DOT__w_rs1;
        CData/*4:0*/ m_topsim__DOT__p__DOT__regs__DOT__w_rs2;
        CData/*0:0*/ m_topsim__DOT__p__DOT__regs__DOT__w_we;
        CData/*4:0*/ m_topsim__DOT__p__DOT__regs__DOT__rd;
        CData/*0:0*/ m_topsim__DOT__p__DOT__ALU_IM__DOT__CLK;
        CData/*0:0*/ m_topsim__DOT__p__DOT__ALU_IM__DOT__RST_X;
        CData/*0:0*/ m_topsim__DOT__p__DOT__ALU_IM__DOT__w_le;
        CData/*2:0*/ m_topsim__DOT__p__DOT__ALU_IM__DOT__w_funct3;
        CData/*6:0*/ m_topsim__DOT__p__DOT__ALU_IM__DOT__w_funct7;
        CData/*0:0*/ m_topsim__DOT__p__DOT__ALU_IM__DOT__w_busy;
        CData/*0:0*/ m_topsim__DOT__p__DOT__ALU_IM__DOT__r_div_first;
        CData/*4:0*/ m_topsim__DOT__p__DOT__ALU_IM__DOT__w_shamt;
        CData/*0:0*/ m_topsim__DOT__p__DOT__ALU_IM__DOT__w_divunit_busy;
        CData/*0:0*/ m_topsim__DOT__p__DOT__ALU_IM__DOT__w_div_req;
        CData/*0:0*/ m_topsim__DOT__p__DOT__ALU_IM__DOT__w_div_init;
        CData/*0:0*/ m_topsim__DOT__p__DOT__ALU_IM__DOT__w_div_signed;
        CData/*0:0*/ m_topsim__DOT__p__DOT__ALU_IM__DOT__divunit__DOT__CLK;
        CData/*0:0*/ m_topsim__DOT__p__DOT__ALU_IM__DOT__divunit__DOT__RST_X;
        CData/*0:0*/ m_topsim__DOT__p__DOT__ALU_IM__DOT__divunit__DOT__w_init;
        CData/*0:0*/ m_topsim__DOT__p__DOT__ALU_IM__DOT__divunit__DOT__w_signed;
        CData/*0:0*/ m_topsim__DOT__p__DOT__ALU_IM__DOT__divunit__DOT__w_busy;
        CData/*0:0*/ m_topsim__DOT__p__DOT__ALU_IM__DOT__divunit__DOT__w_sign_dividend;
        CData/*0:0*/ m_topsim__DOT__p__DOT__ALU_IM__DOT__divunit__DOT__w_sign_divisor;
        CData/*0:0*/ m_topsim__DOT__p__DOT__ALU_IM__DOT__divunit__DOT__divcore__DOT__CLK;
        CData/*0:0*/ m_topsim__DOT__p__DOT__ALU_IM__DOT__divunit__DOT__divcore__DOT__RST_X;
        CData/*0:0*/ m_topsim__DOT__p__DOT__ALU_IM__DOT__divunit__DOT__divcore__DOT__w_init;
        CData/*0:0*/ m_topsim__DOT__p__DOT__ALU_IM__DOT__divunit__DOT__divcore__DOT__w_busy;
        CData/*5:0*/ m_topsim__DOT__p__DOT__ALU_IM__DOT__divunit__DOT__divcore__DOT__r_count;
        CData/*2:0*/ m_topsim__DOT__p__DOT__ALU_B__DOT__w_funct3;
        CData/*0:0*/ m_topsim__DOT__p__DOT__ALU_B__DOT__r_rslt;
        CData/*2:0*/ m_topsim__DOT__p__DOT__ALU_C__DOT__w_funct3;
        CData/*4:0*/ m_topsim__DOT__p__DOT__ALU_A__DOT__w_funct5;
        CData/*0:0*/ m_topsim__DOT__UartTx_init__DOT__CLK;
        CData/*0:0*/ m_topsim__DOT__UartTx_init__DOT__RST_X;
        CData/*0:0*/ m_topsim__DOT__UartTx_init__DOT__WE;
        CData/*7:0*/ m_topsim__DOT__UartTx_init__DOT__DATA;
        CData/*0:0*/ m_topsim__DOT__UartTx_init__DOT__TXD;
        CData/*0:0*/ m_topsim__DOT__UartTx_init__DOT__READY;
        CData/*3:0*/ m_topsim__DOT__UartTx_init__DOT__cnt;
        SData/*15:0*/ m_topsim__DOT__ddr2_dq;
        SData/*12:0*/ m_topsim__DOT__ddr2_addr;
        SData/*15:0*/ m_topsim__DOT__w_led;
        SData/*15:0*/ m_topsim__DOT__mmu__DOT__ddr2_dq;
        SData/*12:0*/ m_topsim__DOT__mmu__DOT__ddr2_addr;
        SData/*15:0*/ m_topsim__DOT__mmu__DOT__w_led;
        SData/*11:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__w_funct12;
        SData/*10:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__lm_mc__DOT__w_addr1;
        SData/*10:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__lm_mc__DOT__w_addr2;
        SData/*11:0*/ m_topsim__DOT__mmu__DOT__disk__DOT__w_addr;
        SData/*8:0*/ m_topsim__DOT__mmu__DOT__UartTx0__DOT__cmd;
        SData/*12:0*/ m_topsim__DOT__mmu__DOT__ploader__DOT__serc__DOT__cnt;
    };
    struct {
        SData/*11:0*/ m_topsim__DOT__mmu__DOT__ploader__DOT__serc__DOT__cnt_start;
        SData/*12:0*/ m_topsim__DOT__mmu__DOT__ploader__DOT__serc__DOT__waitcnt;
        SData/*8:0*/ m_topsim__DOT__mmu__DOT__debug_KEY__DOT__r_waddr;
        SData/*8:0*/ m_topsim__DOT__mmu__DOT__debug_KEY__DOT__r_raddr;
        SData/*11:0*/ m_topsim__DOT__mmu__DOT__debug_KEY__DOT__r_state;
        SData/*11:0*/ m_topsim__DOT__mmu__DOT__debug_KEY__DOT__UartTx0__DOT__r_waitnum;
        SData/*12:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__cache__DOT__r_idx;
        SData/*14:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__cache__DOT__r_tag;
        SData/*12:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__cache__DOT__w_idx;
        SData/*14:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__cache__DOT__w_tag;
        SData/*12:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__cache__DOT__w_maddr;
        SData/*12:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__cache__DOT__w_midx;
        SData/*14:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__cache__DOT__w_mtag;
        SData/*12:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__cache__DOT__mem__DOT__w_addr;
        SData/*15:0*/ m_topsim__DOT__p__DOT__r_ir16;
        SData/*11:0*/ m_topsim__DOT__p__DOT__r_funct12;
        SData/*15:0*/ m_topsim__DOT__p__DOT__r_if_irl;
        SData/*11:0*/ m_topsim__DOT__p__DOT__w_csr_addr;
        SData/*8:0*/ m_topsim__DOT__UartTx_init__DOT__cmd;
        IData/*31:0*/ m_topsim__DOT__w_insn_data;
        IData/*31:0*/ m_topsim__DOT__w_insn_addr;
        IData/*31:0*/ m_topsim__DOT__w_data_data;
        IData/*31:0*/ m_topsim__DOT__w_data_wdata;
        IData/*31:0*/ m_topsim__DOT__w_data_addr;
        IData/*31:0*/ m_topsim__DOT__w_priv;
        IData/*31:0*/ m_topsim__DOT__w_satp;
        IData/*31:0*/ m_topsim__DOT__w_mstatus;
        IData/*31:0*/ m_topsim__DOT__w_mip;
        IData/*31:0*/ m_topsim__DOT__w_wmip;
        IData/*31:0*/ m_topsim__DOT__w_pagefault;
        IData/*31:0*/ m_topsim__DOT__i;
        IData/*31:0*/ m_topsim__DOT__j;
        IData/*31:0*/ m_topsim__DOT__fp;
        IData/*31:0*/ m_topsim__DOT__r_cnt;
        IData/*16:0*/ m_topsim__DOT__imemaddr;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__w_insn_addr;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__w_data_addr;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__w_data_wdata;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__w_insn_data;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__w_data_data;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__w_priv;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__w_satp;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__w_mstatus;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__w_mip;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__w_wmip;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__w_pagefault;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__w_checksum;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__physical_addr;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__L1_pte;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__L0_pte;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__r_tohost;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__plic_served_irq;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__plic_pending_irq;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__r_plic_odata;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__r_clint_odata;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__r_mc_qnum;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__r_mc_qsel;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__r_mc_done;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__w_dram_odata;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__w_mc_addr;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__w_mc_wdata;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__w_mem_wdata;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__v_addr;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__vpn1;
    };
    struct {
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__L1_pte_addr;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__L1_paddr;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__L1_p_addr;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__vpn0;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__L0_pte_addr;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__L0_paddr;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__L0_p_addr;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__L1_pte_write;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__L0_pte_write;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__w_pte_waddr;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__w_pte_wdata;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__r_tlb_addr;
        IData/*21:0*/ m_topsim__DOT__mmu__DOT__w_tlb_inst_r_addr;
        IData/*21:0*/ m_topsim__DOT__mmu__DOT__w_tlb_data_r_addr;
        IData/*21:0*/ m_topsim__DOT__mmu__DOT__w_tlb_data_w_addr;
        IData/*21:0*/ m_topsim__DOT__mmu__DOT__w_tlb_wdata;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__r_tlb_pte_addr;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__w_insn_paddr;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__w_mem_paddr;
        IData/*27:0*/ m_topsim__DOT__mmu__DOT__w_offset;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__w_dram_wdata;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__w_dram_addr;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__w_cons_data;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__w_cons_addr;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__w_cons_qnum;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__w_cons_qsel;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__w_disk_data;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__w_disk_addr;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__w_disk_qnum;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__w_disk_qsel;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__r_data_data;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__r_mc_arg;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__w_mc_arg;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__w_cons_irq;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__w_disk_irq;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__w_virt_irq;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__w_plic_pending_irq_nxt;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__w_plic_mask;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__w_plic_served_irq_nxt;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__r_wmip;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__r_plic_pending_irq_t;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__r_plic_served_irq_t;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__w_plic_mask_nxt;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__w_pl_init_addr;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__w_pl_init_data;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__r_checksum;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__r_initaddr;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__r_initaddr2;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__r_initaddr3;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__r_zeroaddr;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__w_dram_addr_t;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__w_dram_addr_t2;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__w_dram_wdata_t;
        IData/*19:0*/ m_topsim__DOT__mmu__DOT__TLB_inst_r__DOT__w_waddr;
        IData/*19:0*/ m_topsim__DOT__mmu__DOT__TLB_inst_r__DOT__w_raddr;
        IData/*21:0*/ m_topsim__DOT__mmu__DOT__TLB_inst_r__DOT__w_idata;
        IData/*21:0*/ m_topsim__DOT__mmu__DOT__TLB_inst_r__DOT__w_odata;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__TLB_inst_r__DOT__i;
        IData/*17:0*/ m_topsim__DOT__mmu__DOT__TLB_inst_r__DOT__w_rtag;
        IData/*17:0*/ m_topsim__DOT__mmu__DOT__TLB_inst_r__DOT__w_wtag;
        IData/*19:0*/ m_topsim__DOT__mmu__DOT__TLB_data_r__DOT__w_waddr;
        IData/*19:0*/ m_topsim__DOT__mmu__DOT__TLB_data_r__DOT__w_raddr;
        IData/*21:0*/ m_topsim__DOT__mmu__DOT__TLB_data_r__DOT__w_idata;
        IData/*21:0*/ m_topsim__DOT__mmu__DOT__TLB_data_r__DOT__w_odata;
    };
    struct {
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__TLB_data_r__DOT__i;
        IData/*17:0*/ m_topsim__DOT__mmu__DOT__TLB_data_r__DOT__w_rtag;
        IData/*17:0*/ m_topsim__DOT__mmu__DOT__TLB_data_r__DOT__w_wtag;
        IData/*19:0*/ m_topsim__DOT__mmu__DOT__TLB_data_w__DOT__w_waddr;
        IData/*19:0*/ m_topsim__DOT__mmu__DOT__TLB_data_w__DOT__w_raddr;
        IData/*21:0*/ m_topsim__DOT__mmu__DOT__TLB_data_w__DOT__w_idata;
        IData/*21:0*/ m_topsim__DOT__mmu__DOT__TLB_data_w__DOT__w_odata;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__TLB_data_w__DOT__i;
        IData/*17:0*/ m_topsim__DOT__mmu__DOT__TLB_data_w__DOT__w_rtag;
        IData/*17:0*/ m_topsim__DOT__mmu__DOT__TLB_data_w__DOT__w_wtag;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__w_mic_addr;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__w_data;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__w_mic_wdata;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__r_pc;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__r_ir;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__r_imm;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__r_rrs1;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__r_rrs2;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__r_rslt;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__r_dram_data;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__w_mem_rdata;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__w_reg_d;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__w_ir;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__w_imm;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__w_rrs1;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__w_rrs2;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__r_mic_addr;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__w_alu_i_rslt;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__w_in2;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__r_jmp_pc;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__w_lcm_data;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__w_mic_insn_addr;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__w_mic_insn_data;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__w_wdata_t;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__w_odata1;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__w_odata2;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__w_odata2_t;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__w_odata2_t2;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__w_odata2_lb;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__w_odata2_lbu;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__w_odata2_lh;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__w_odata2_lhu;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__imm_gen0__DOT__w_inst;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__imm_gen0__DOT__r_imm;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__imm_gen0__DOT__imm_I;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__imm_gen0__DOT__imm_S;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__imm_gen0__DOT__imm_B;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__imm_gen0__DOT__imm_U;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__imm_gen0__DOT__imm_J;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__imm_gen0__DOT__imm_C;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__regs__DOT__w_rdata1;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__regs__DOT__w_rdata2;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__regs__DOT__w_wdata;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__regs__DOT__i;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__ALU_I__DOT__w_in1;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__ALU_I__DOT__w_in2;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__ALU_I__DOT__r_rslt;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__ALU_I__DOT__w_sin1;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__ALU_I__DOT__w_sin2;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__ALU_B__DOT__w_in1;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__ALU_B__DOT__w_in2;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__ALU_B__DOT__w_sin1;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__ALU_B__DOT__w_sin2;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__lm_mc__DOT__w_idata;
    };
    struct {
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__lm_mc__DOT__r_odata1;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__mc__DOT__lm_mc__DOT__r_odata2;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__console__DOT__w_addr_t;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__console__DOT__w_idata;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__console__DOT__w_iirq;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__console__DOT__w_odata;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__console__DOT__w_oirq;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__console__DOT__w_qnum;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__console__DOT__w_qsel;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__console__DOT__MagicValue;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__console__DOT__Version;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__console__DOT__DeviceID;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__console__DOT__VendorID;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__console__DOT__DeviceFeatures;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__console__DOT__QueueNumMax;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__console__DOT__ConfigGeneration;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__console__DOT__DeviceFeaturesSel;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__console__DOT__DriverFeatures;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__console__DOT__DriverFeaturesSel;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__console__DOT__InterruptStatus;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__console__DOT__InterruptAcknowledge;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__console__DOT__Status;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__console__DOT__QueueSel;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__console__DOT__QueueNum;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__console__DOT__i;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__console__DOT__r_rdata;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__console__DOT__w_irqmask;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__console__DOT__w_oirq1;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__console__DOT__w_oirq2;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__disk__DOT__w_addr_t;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__disk__DOT__w_idata;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__disk__DOT__w_iirq;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__disk__DOT__w_odata;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__disk__DOT__w_oirq;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__disk__DOT__w_qnum;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__disk__DOT__w_qsel;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__disk__DOT__MagicValue;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__disk__DOT__Version;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__disk__DOT__DeviceID;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__disk__DOT__VendorID;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__disk__DOT__DeviceFeatures;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__disk__DOT__QueueNumMax;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__disk__DOT__ConfigGeneration;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__disk__DOT__DeviceFeaturesSel;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__disk__DOT__DriverFeatures;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__disk__DOT__DriverFeaturesSel;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__disk__DOT__InterruptStatus;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__disk__DOT__InterruptAcknowledge;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__disk__DOT__Status;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__disk__DOT__QueueSel;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__disk__DOT__QueueNum;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__disk__DOT__i;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__disk__DOT__rdata;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__disk__DOT__w_irqmask;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__disk__DOT__w_oirq1;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__disk__DOT__w_oirq2;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__UartTx0__DOT__waitnum;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__ploader__DOT__ADDR;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__ploader__DOT__DATA;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__ploader__DOT__waddr;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__debug_KEY__DOT__w_mtime;
        VlWide<6>/*184:0*/ m_topsim__DOT__mmu__DOT__debug_KEY__DOT__UartTx0__DOT__r_cmd;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__debug_KEY__DOT__UartTx0__DOT__r_cnt;
        VlWide<6>/*183:0*/ m_topsim__DOT__mmu__DOT__debug_KEY__DOT__UartTx0__DOT__r_dataout;
    };
    struct {
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__w_addr;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__w_odata;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__w_wdata;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__w_mtime;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__r_addr;
        VlWide<4>/*127:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__r_odata;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__e_data;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__w_dram_addr;
        VlWide<4>/*127:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__w_dram_odata;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__w_cache_addr;
        VlWide<4>/*127:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__w_cache_idata;
        VlWide<4>/*127:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__w_cache_odata;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__w_odata_t;
        IData/*27:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__cache__DOT__w_addr;
        VlWide<4>/*127:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__cache__DOT__w_idata;
        VlWide<4>/*127:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__cache__DOT__w_odata;
        VlWide<5>/*143:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__cache__DOT__w_mwdata;
        VlWide<5>/*143:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__cache__DOT__w_modata;
        VlWide<4>/*127:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__cache__DOT__w_mdata;
        VlWide<5>/*143:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__cache__DOT__mem__DOT__w_idata;
        VlWide<5>/*143:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__cache__DOT__mem__DOT__r_odata;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__cache__DOT__mem__DOT__i;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__idbmem__DOT__w_addr;
        VlWide<4>/*127:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__idbmem__DOT__w_odata;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__idbmem__DOT__w_wdata;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__idbmem__DOT__r_addr;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__idbmem__DOT__r_cnt;
        VlWide<4>/*127:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__idbmem__DOT__r_odata;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__idbmem__DOT__w_maddr;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__idbmem__DOT__w_maddr_tw;
        IData/*31:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__idbmem__DOT__w_maddr_tr;
        IData/*31:0*/ m_topsim__DOT__p__DOT__w_insn_data;
        IData/*31:0*/ m_topsim__DOT__p__DOT__w_data_data;
        IData/*31:0*/ m_topsim__DOT__p__DOT__w_wmip;
        IData/*31:0*/ m_topsim__DOT__p__DOT__w_pagefault;
        IData/*31:0*/ m_topsim__DOT__p__DOT__w_core_odata;
        IData/*31:0*/ m_topsim__DOT__p__DOT__w_data_wdata;
        IData/*31:0*/ m_topsim__DOT__p__DOT__w_insn_addr;
        IData/*31:0*/ m_topsim__DOT__p__DOT__w_data_addr;
        IData/*31:0*/ m_topsim__DOT__p__DOT__w_priv;
        IData/*31:0*/ m_topsim__DOT__p__DOT__w_satp;
        IData/*31:0*/ m_topsim__DOT__p__DOT__w_mstatus;
        IData/*31:0*/ m_topsim__DOT__p__DOT__w_mip;
        IData/*31:0*/ m_topsim__DOT__p__DOT__w_core_pc;
        IData/*31:0*/ m_topsim__DOT__p__DOT__w_core_ir;
        IData/*31:0*/ m_topsim__DOT__p__DOT__pc;
        IData/*31:0*/ m_topsim__DOT__p__DOT__mstatus;
        IData/*31:0*/ m_topsim__DOT__p__DOT__mtvec;
        IData/*31:0*/ m_topsim__DOT__p__DOT__mscratch;
        IData/*31:0*/ m_topsim__DOT__p__DOT__mepc;
        IData/*31:0*/ m_topsim__DOT__p__DOT__mcause;
        IData/*31:0*/ m_topsim__DOT__p__DOT__mtval;
        IData/*31:0*/ m_topsim__DOT__p__DOT__mhartid;
        IData/*31:0*/ m_topsim__DOT__p__DOT__misa;
        IData/*31:0*/ m_topsim__DOT__p__DOT__mie;
        IData/*31:0*/ m_topsim__DOT__p__DOT__mip;
        IData/*31:0*/ m_topsim__DOT__p__DOT__medeleg;
        IData/*31:0*/ m_topsim__DOT__p__DOT__mideleg;
        IData/*31:0*/ m_topsim__DOT__p__DOT__mcounteren;
        IData/*31:0*/ m_topsim__DOT__p__DOT__stvec;
        IData/*31:0*/ m_topsim__DOT__p__DOT__sscratch;
        IData/*31:0*/ m_topsim__DOT__p__DOT__sepc;
        IData/*31:0*/ m_topsim__DOT__p__DOT__scause;
        IData/*31:0*/ m_topsim__DOT__p__DOT__stval;
    };
    struct {
        IData/*31:0*/ m_topsim__DOT__p__DOT__satp;
        IData/*31:0*/ m_topsim__DOT__p__DOT__scounteren;
        IData/*31:0*/ m_topsim__DOT__p__DOT__load_res;
        IData/*31:0*/ m_topsim__DOT__p__DOT__pending_tval;
        IData/*31:0*/ m_topsim__DOT__p__DOT__pending_exception;
        IData/*31:0*/ m_topsim__DOT__p__DOT__r_cpc;
        IData/*31:0*/ m_topsim__DOT__p__DOT__r_ir_org;
        IData/*31:0*/ m_topsim__DOT__p__DOT__r_ir;
        IData/*31:0*/ m_topsim__DOT__p__DOT__r_imm;
        IData/*31:0*/ m_topsim__DOT__p__DOT__r_rrs1;
        IData/*31:0*/ m_topsim__DOT__p__DOT__r_rrs2;
        IData/*31:0*/ m_topsim__DOT__p__DOT__r_rcsr;
        IData/*31:0*/ m_topsim__DOT__p__DOT__r_alu_in2;
        IData/*31:0*/ m_topsim__DOT__p__DOT__r_jmp_pc;
        IData/*31:0*/ m_topsim__DOT__p__DOT__r_mem_addr;
        IData/*31:0*/ m_topsim__DOT__p__DOT__r_wb_data;
        IData/*31:0*/ m_topsim__DOT__p__DOT__r_wb_data_csr;
        IData/*31:0*/ m_topsim__DOT__p__DOT__r_mem_rdata;
        IData/*31:0*/ m_topsim__DOT__p__DOT__r_atom_wdata;
        IData/*31:0*/ m_topsim__DOT__p__DOT__r_rcsr_t;
        IData/*31:0*/ m_topsim__DOT__p__DOT__irq_num;
        IData/*31:0*/ m_topsim__DOT__p__DOT__w_wb_r_data;
        IData/*31:0*/ m_topsim__DOT__p__DOT__w_interrupt_mask;
        IData/*31:0*/ m_topsim__DOT__p__DOT__w_irq_t;
        IData/*31:0*/ m_topsim__DOT__p__DOT__w_vadr1;
        IData/*31:0*/ m_topsim__DOT__p__DOT__w_vadr2;
        IData/*31:0*/ m_topsim__DOT__p__DOT__r_insn_addr;
        IData/*31:0*/ m_topsim__DOT__p__DOT__w_ir_org;
        IData/*31:0*/ m_topsim__DOT__p__DOT__w_ir_t;
        IData/*31:0*/ m_topsim__DOT__p__DOT__w_ir;
        IData/*31:0*/ m_topsim__DOT__p__DOT__w_imm;
        IData/*31:0*/ m_topsim__DOT__p__DOT__w_rrs1;
        IData/*31:0*/ m_topsim__DOT__p__DOT__w_rrs2;
        IData/*31:0*/ m_topsim__DOT__p__DOT__w_sin1;
        IData/*31:0*/ m_topsim__DOT__p__DOT__w_sin2;
        IData/*31:0*/ m_topsim__DOT__p__DOT__w_mem_addr;
        IData/*31:0*/ m_topsim__DOT__p__DOT__w_alu_im_rslt;
        IData/*31:0*/ m_topsim__DOT__p__DOT__w_alu_c_rslt;
        IData/*31:0*/ m_topsim__DOT__p__DOT__w_mem_rdata;
        IData/*31:0*/ m_topsim__DOT__p__DOT__w_alu_a_rslt;
        IData/*31:0*/ m_topsim__DOT__p__DOT__r_data_wdata;
        IData/*31:0*/ m_topsim__DOT__p__DOT__r_mstatus_t;
        IData/*31:0*/ m_topsim__DOT__p__DOT__w_mstatus_nxt;
        IData/*31:0*/ m_topsim__DOT__p__DOT__pending_interrupts;
        IData/*31:0*/ m_topsim__DOT__p__DOT__enable_interrupts;
        IData/*31:0*/ m_topsim__DOT__p__DOT__cause;
        IData/*31:0*/ m_topsim__DOT__p__DOT__w_deleg;
        IData/*31:0*/ m_topsim__DOT__p__DOT__w_sstatus_t;
        IData/*31:0*/ m_topsim__DOT__p__DOT__w_mstatus_t;
        IData/*31:0*/ m_topsim__DOT__p__DOT__w_sstatus;
        IData/*31:0*/ m_topsim__DOT__p__DOT__w_sstatus_t1;
        IData/*31:0*/ m_topsim__DOT__p__DOT__w_sstatus_t2;
        IData/*31:0*/ m_topsim__DOT__p__DOT__w_sstatus_t3;
        IData/*31:0*/ m_topsim__DOT__p__DOT__w_mstatus_t1;
        IData/*31:0*/ m_topsim__DOT__p__DOT__w_mstatus_t2;
        IData/*31:0*/ m_topsim__DOT__p__DOT__w_mstatus_t3;
        IData/*31:0*/ m_topsim__DOT__p__DOT__w_data_t;
        IData/*31:0*/ m_topsim__DOT__p__DOT__w_mod;
        IData/*31:0*/ m_topsim__DOT__p__DOT__decomp0__DOT__w_ic;
        IData/*31:0*/ m_topsim__DOT__p__DOT__decomp0__DOT__r_iw;
        IData/*31:0*/ m_topsim__DOT__p__DOT__decomp0__DOT__w_c0_uimm1;
        IData/*31:0*/ m_topsim__DOT__p__DOT__decomp0__DOT__w_c0_uimm2;
        IData/*31:0*/ m_topsim__DOT__p__DOT__decomp0__DOT__w_c0_nzuimm;
        IData/*31:0*/ m_topsim__DOT__p__DOT__decomp0__DOT__w_c1_nzimm;
    };
    struct {
        IData/*31:0*/ m_topsim__DOT__p__DOT__decomp0__DOT__w_c1_imm1;
        IData/*31:0*/ m_topsim__DOT__p__DOT__decomp0__DOT__w_c1_imm2;
        IData/*31:0*/ m_topsim__DOT__p__DOT__decomp0__DOT__w_c1_imm3;
        IData/*31:0*/ m_topsim__DOT__p__DOT__decomp0__DOT__w_c1_imm4;
        IData/*31:0*/ m_topsim__DOT__p__DOT__decomp0__DOT__w_c2_uimm1;
        IData/*31:0*/ m_topsim__DOT__p__DOT__decomp0__DOT__w_c2_uimm2;
        IData/*31:0*/ m_topsim__DOT__p__DOT__decomp0__DOT__w_c2_uimm3;
        IData/*31:0*/ m_topsim__DOT__p__DOT__decomp0__DOT__w_c2_uimm4;
        IData/*31:0*/ m_topsim__DOT__p__DOT__decomp0__DOT__w_c2_nzuimm;
        IData/*31:0*/ m_topsim__DOT__p__DOT__imm_gen0__DOT__w_inst;
        IData/*31:0*/ m_topsim__DOT__p__DOT__imm_gen0__DOT__r_imm;
        IData/*31:0*/ m_topsim__DOT__p__DOT__imm_gen0__DOT__imm_I;
        IData/*31:0*/ m_topsim__DOT__p__DOT__imm_gen0__DOT__imm_S;
        IData/*31:0*/ m_topsim__DOT__p__DOT__imm_gen0__DOT__imm_B;
        IData/*31:0*/ m_topsim__DOT__p__DOT__imm_gen0__DOT__imm_U;
        IData/*31:0*/ m_topsim__DOT__p__DOT__imm_gen0__DOT__imm_J;
        IData/*31:0*/ m_topsim__DOT__p__DOT__imm_gen0__DOT__imm_C;
        IData/*31:0*/ m_topsim__DOT__p__DOT__regs__DOT__w_rdata1;
        IData/*31:0*/ m_topsim__DOT__p__DOT__regs__DOT__w_rdata2;
        IData/*31:0*/ m_topsim__DOT__p__DOT__regs__DOT__w_wdata;
        IData/*31:0*/ m_topsim__DOT__p__DOT__regs__DOT__i;
        IData/*31:0*/ m_topsim__DOT__p__DOT__ALU_IM__DOT__w_in1;
        IData/*31:0*/ m_topsim__DOT__p__DOT__ALU_IM__DOT__w_in2;
        IData/*31:0*/ m_topsim__DOT__p__DOT__ALU_IM__DOT__r_rslt;
        IData/*31:0*/ m_topsim__DOT__p__DOT__ALU_IM__DOT__w_sin1;
        IData/*31:0*/ m_topsim__DOT__p__DOT__ALU_IM__DOT__w_sin2;
        IData/*31:0*/ m_topsim__DOT__p__DOT__ALU_IM__DOT__divunit__DOT__w_dividend;
        IData/*31:0*/ m_topsim__DOT__p__DOT__ALU_IM__DOT__divunit__DOT__w_divisor;
        IData/*31:0*/ m_topsim__DOT__p__DOT__ALU_IM__DOT__divunit__DOT__w_uint_dividend;
        IData/*31:0*/ m_topsim__DOT__p__DOT__ALU_IM__DOT__divunit__DOT__w_uint_divisor;
        IData/*31:0*/ m_topsim__DOT__p__DOT__ALU_IM__DOT__divunit__DOT__divcore__DOT__w_dividend;
        IData/*31:0*/ m_topsim__DOT__p__DOT__ALU_IM__DOT__divunit__DOT__divcore__DOT__w_divisor;
        IData/*31:0*/ m_topsim__DOT__p__DOT__ALU_IM__DOT__divunit__DOT__divcore__DOT__r_divisor;
        IData/*31:0*/ m_topsim__DOT__p__DOT__ALU_B__DOT__w_in1;
        IData/*31:0*/ m_topsim__DOT__p__DOT__ALU_B__DOT__w_in2;
        IData/*31:0*/ m_topsim__DOT__p__DOT__ALU_B__DOT__w_sin1;
        IData/*31:0*/ m_topsim__DOT__p__DOT__ALU_B__DOT__w_sin2;
        IData/*31:0*/ m_topsim__DOT__p__DOT__ALU_C__DOT__w_rcsr;
        IData/*31:0*/ m_topsim__DOT__p__DOT__ALU_C__DOT__w_rrs1;
        IData/*31:0*/ m_topsim__DOT__p__DOT__ALU_C__DOT__w_imm;
        IData/*31:0*/ m_topsim__DOT__p__DOT__ALU_C__DOT__r_rslt;
        IData/*31:0*/ m_topsim__DOT__p__DOT__ALU_A__DOT__w_in1;
        IData/*31:0*/ m_topsim__DOT__p__DOT__ALU_A__DOT__w_in2;
        IData/*31:0*/ m_topsim__DOT__p__DOT__ALU_A__DOT__r_rslt;
        IData/*31:0*/ m_topsim__DOT__p__DOT__ALU_A__DOT__w_sin1;
        IData/*31:0*/ m_topsim__DOT__p__DOT__ALU_A__DOT__w_sin2;
        IData/*31:0*/ m_topsim__DOT__UartTx_init__DOT__waitnum;
        QData/*63:0*/ m_topsim__DOT__w_mtime;
        QData/*63:0*/ m_topsim__DOT__w_mtimecmp;
        QData/*63:0*/ m_topsim__DOT__w_wmtimecmp;
        QData/*63:0*/ m_topsim__DOT__mmu__DOT__w_mtime;
        QData/*63:0*/ m_topsim__DOT__mmu__DOT__w_mtimecmp;
        QData/*63:0*/ m_topsim__DOT__mmu__DOT__w_wmtimecmp;
        QData/*39:0*/ m_topsim__DOT__mmu__DOT__debug_KEY__DOT__r_uartdata;
        QData/*39:0*/ m_topsim__DOT__mmu__DOT__debug_KEY__DOT__UartTx0__DOT__w_data;
        QData/*63:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__e_cnt;
        QData/*63:0*/ m_topsim__DOT__mmu__DOT__idbmem__DOT__e_hit;
        QData/*63:0*/ m_topsim__DOT__p__DOT__w_wmtimecmp;
        QData/*63:0*/ m_topsim__DOT__p__DOT__w_mtime;
        QData/*63:0*/ m_topsim__DOT__p__DOT__w_mtimecmp;
        QData/*63:0*/ m_topsim__DOT__p__DOT__mtime;
        QData/*63:0*/ m_topsim__DOT__p__DOT__mtimecmp;
        QData/*63:0*/ m_topsim__DOT__p__DOT__e_icount;
        QData/*63:0*/ m_topsim__DOT__p__DOT__w_mul_SS;
    };
    struct {
        QData/*63:0*/ m_topsim__DOT__p__DOT__w_mul_SU;
        QData/*63:0*/ m_topsim__DOT__p__DOT__w_mul_UU;
        QData/*63:0*/ m_topsim__DOT__p__DOT__r_mul_SS;
        QData/*63:0*/ m_topsim__DOT__p__DOT__r_mul_SU;
        QData/*63:0*/ m_topsim__DOT__p__DOT__r_mul_UU;
        QData/*63:0*/ m_topsim__DOT__p__DOT__ALU_IM__DOT__w_mul_SS;
        QData/*63:0*/ m_topsim__DOT__p__DOT__ALU_IM__DOT__w_mul_SU;
        QData/*63:0*/ m_topsim__DOT__p__DOT__ALU_IM__DOT__w_mul_UU;
        QData/*63:0*/ m_topsim__DOT__p__DOT__ALU_IM__DOT__w_divunit_rslt;
        QData/*63:0*/ m_topsim__DOT__p__DOT__ALU_IM__DOT__w_div_rslt;
        QData/*63:0*/ m_topsim__DOT__p__DOT__ALU_IM__DOT__divunit__DOT__w_rslt;
        QData/*63:0*/ m_topsim__DOT__p__DOT__ALU_IM__DOT__divunit__DOT__w_uint_rslt;
        QData/*63:0*/ m_topsim__DOT__p__DOT__ALU_IM__DOT__divunit__DOT__divcore__DOT__r_rslt;
        QData/*32:0*/ m_topsim__DOT__p__DOT__ALU_IM__DOT__divunit__DOT__divcore__DOT__w_differ;
        VlUnpacked<CData/*7:0*/, 67108864> m_topsim__DOT__mem_bbl;
        VlUnpacked<CData/*7:0*/, 8192> m_topsim__DOT__mem_mc;
        VlUnpacked<CData/*7:0*/, 67108864> m_topsim__DOT__mem_disk;
        VlUnpacked<CData/*7:0*/, 16> m_topsim__DOT__mmu__DOT__cons_fifo;
        VlUnpacked<QData/*39:0*/, 4> m_topsim__DOT__mmu__DOT__TLB_inst_r__DOT__mem;
        VlUnpacked<QData/*39:0*/, 4> m_topsim__DOT__mmu__DOT__TLB_data_r__DOT__mem;
        VlUnpacked<QData/*39:0*/, 4> m_topsim__DOT__mmu__DOT__TLB_data_w__DOT__mem;
        VlUnpacked<IData/*31:0*/, 32> m_topsim__DOT__mmu__DOT__mc__DOT__regs__DOT__mem;
        VlUnpacked<IData/*31:0*/, 2048> m_topsim__DOT__mmu__DOT__mc__DOT__lm_mc__DOT__mem;
        VlUnpacked<CData/*7:0*/, 256> m_topsim__DOT__mmu__DOT__console__DOT__Config;
        VlUnpacked<IData/*31:0*/, 18> m_topsim__DOT__mmu__DOT__console__DOT__Queue;
        VlUnpacked<CData/*7:0*/, 256> m_topsim__DOT__mmu__DOT__disk__DOT__Config;
        VlUnpacked<IData/*31:0*/, 36> m_topsim__DOT__mmu__DOT__disk__DOT__Queue;
        VlUnpacked<QData/*39:0*/, 512> m_topsim__DOT__mmu__DOT__debug_KEY__DOT__buff;
        VlUnpacked<VlWide<5>/*143:0*/, 8192> m_topsim__DOT__mmu__DOT__idbmem__DOT__cache__DOT__mem__DOT__mem;
        VlUnpacked<CData/*7:0*/, 134217728> m_topsim__DOT__mmu__DOT__idbmem__DOT__idbmem__DOT__mem;
        VlUnpacked<IData/*31:0*/, 32> m_topsim__DOT__p__DOT__regs__DOT__mem;
    };
    
    // LOCAL VARIABLES
    // Internals; generally not touched by application code
    CData/*1:0*/ __Vdly__m_topsim__DOT__mmu__DOT__r_mc_mode;
    CData/*1:0*/ __Vdly__m_topsim__DOT__mmu__DOT__mc__DOT__r_state;
    CData/*3:0*/ __Vdly__m_topsim__DOT__mmu__DOT__ploader__DOT__serc__DOT__stage;
    CData/*0:0*/ __Vdlyvset__m_topsim__DOT__mmu__DOT__debug_KEY__DOT__buff__v0;
    CData/*1:0*/ __Vdly__m_topsim__DOT__p__DOT__priv;
    CData/*0:0*/ __Vdly__m_topsim__DOT__tx_ready;
    CData/*0:0*/ __Vclklast__TOP__CLK;
    SData/*11:0*/ __Vdly__m_topsim__DOT__mmu__DOT__ploader__DOT__serc__DOT__cnt_start;
    SData/*8:0*/ __Vdlyvdim0__m_topsim__DOT__mmu__DOT__debug_KEY__DOT__buff__v0;
    SData/*8:0*/ __Vdly__m_topsim__DOT__mmu__DOT__debug_KEY__DOT__r_waddr;
    SData/*8:0*/ __Vdly__m_topsim__DOT__mmu__DOT__debug_KEY__DOT__r_raddr;
    SData/*11:0*/ __Vdly__m_topsim__DOT__mmu__DOT__debug_KEY__DOT__r_state;
    IData/*31:0*/ m_topsim__DOT__mmu__DOT__console__DOT____Vlvbound2;
    IData/*31:0*/ m_topsim__DOT__mmu__DOT__console__DOT____Vlvbound3;
    IData/*31:0*/ m_topsim__DOT__mmu__DOT__console__DOT____Vlvbound4;
    IData/*31:0*/ m_topsim__DOT__mmu__DOT__console__DOT____Vlvbound5;
    IData/*31:0*/ m_topsim__DOT__mmu__DOT__console__DOT____Vlvbound6;
    IData/*31:0*/ m_topsim__DOT__mmu__DOT__console__DOT____Vlvbound7;
    IData/*31:0*/ m_topsim__DOT__mmu__DOT__disk__DOT____Vlvbound2;
    IData/*31:0*/ m_topsim__DOT__mmu__DOT__disk__DOT____Vlvbound3;
    IData/*31:0*/ m_topsim__DOT__mmu__DOT__disk__DOT____Vlvbound4;
    IData/*31:0*/ m_topsim__DOT__mmu__DOT__disk__DOT____Vlvbound5;
    IData/*31:0*/ m_topsim__DOT__mmu__DOT__disk__DOT____Vlvbound6;
    IData/*31:0*/ m_topsim__DOT__mmu__DOT__disk__DOT____Vlvbound7;
    IData/*31:0*/ __Vdly__m_topsim__DOT__r_cnt;
    IData/*31:0*/ __Vdly__m_topsim__DOT__mmu__DOT__r_tohost;
    IData/*31:0*/ __Vdly__m_topsim__DOT__mmu__DOT__mc__DOT__r_pc;
    IData/*31:0*/ __Vdly__m_topsim__DOT__mmu__DOT__ploader__DOT__waddr;
    IData/*31:0*/ __Vdly__m_topsim__DOT__p__DOT__r_wb_data;
    IData/*31:0*/ __Vdly__m_topsim__DOT__p__DOT__pc;
    QData/*39:0*/ __Vdlyvval__m_topsim__DOT__mmu__DOT__debug_KEY__DOT__buff__v0;
    QData/*63:0*/ __Vdly__m_topsim__DOT__p__DOT__mtime;
    
    // INTERNAL VARIABLES
    // Internals; generally not touched by application code
    Vm_topsim__Syms* __VlSymsp;  // Symbol table
    
    // PARAMETERS
    // Parameters marked /*verilator public*/ for use by application code
    enum _IDatam_topsim__DOT__mmu__DOT__TLB_inst_r__DOT__ADDR_WIDTH { m_topsim__DOT__mmu__DOT__TLB_inst_r__DOT__ADDR_WIDTH = 0x14U};
    static const IData var_m_topsim__DOT__mmu__DOT__TLB_inst_r__DOT__ADDR_WIDTH;
    enum _IDatam_topsim__DOT__mmu__DOT__TLB_inst_r__DOT__D_WIDTH { m_topsim__DOT__mmu__DOT__TLB_inst_r__DOT__D_WIDTH = 0x16U};
    static const IData var_m_topsim__DOT__mmu__DOT__TLB_inst_r__DOT__D_WIDTH;
    enum _IDatam_topsim__DOT__mmu__DOT__TLB_inst_r__DOT__ENTRY { m_topsim__DOT__mmu__DOT__TLB_inst_r__DOT__ENTRY = 4U};
    static const IData var_m_topsim__DOT__mmu__DOT__TLB_inst_r__DOT__ENTRY;
    enum _IDatam_topsim__DOT__mmu__DOT__TLB_data_r__DOT__ADDR_WIDTH { m_topsim__DOT__mmu__DOT__TLB_data_r__DOT__ADDR_WIDTH = 0x14U};
    static const IData var_m_topsim__DOT__mmu__DOT__TLB_data_r__DOT__ADDR_WIDTH;
    enum _IDatam_topsim__DOT__mmu__DOT__TLB_data_r__DOT__D_WIDTH { m_topsim__DOT__mmu__DOT__TLB_data_r__DOT__D_WIDTH = 0x16U};
    static const IData var_m_topsim__DOT__mmu__DOT__TLB_data_r__DOT__D_WIDTH;
    enum _IDatam_topsim__DOT__mmu__DOT__TLB_data_r__DOT__ENTRY { m_topsim__DOT__mmu__DOT__TLB_data_r__DOT__ENTRY = 4U};
    static const IData var_m_topsim__DOT__mmu__DOT__TLB_data_r__DOT__ENTRY;
    enum _IDatam_topsim__DOT__mmu__DOT__TLB_data_w__DOT__ADDR_WIDTH { m_topsim__DOT__mmu__DOT__TLB_data_w__DOT__ADDR_WIDTH = 0x14U};
    static const IData var_m_topsim__DOT__mmu__DOT__TLB_data_w__DOT__ADDR_WIDTH;
    enum _IDatam_topsim__DOT__mmu__DOT__TLB_data_w__DOT__D_WIDTH { m_topsim__DOT__mmu__DOT__TLB_data_w__DOT__D_WIDTH = 0x16U};
    static const IData var_m_topsim__DOT__mmu__DOT__TLB_data_w__DOT__D_WIDTH;
    enum _IDatam_topsim__DOT__mmu__DOT__TLB_data_w__DOT__ENTRY { m_topsim__DOT__mmu__DOT__TLB_data_w__DOT__ENTRY = 4U};
    static const IData var_m_topsim__DOT__mmu__DOT__TLB_data_w__DOT__ENTRY;
    enum _IDatam_topsim__DOT__mmu__DOT__idbmem__DOT__MEM_SIZE { m_topsim__DOT__mmu__DOT__idbmem__DOT__MEM_SIZE = 0x8000000U};
    static const IData var_m_topsim__DOT__mmu__DOT__idbmem__DOT__MEM_SIZE;
    enum _IDatam_topsim__DOT__mmu__DOT__idbmem__DOT__cache__DOT__ADDR_WIDTH { m_topsim__DOT__mmu__DOT__idbmem__DOT__cache__DOT__ADDR_WIDTH = 0x1cU};
    static const IData var_m_topsim__DOT__mmu__DOT__idbmem__DOT__cache__DOT__ADDR_WIDTH;
    enum _IDatam_topsim__DOT__mmu__DOT__idbmem__DOT__cache__DOT__D_WIDTH { m_topsim__DOT__mmu__DOT__idbmem__DOT__cache__DOT__D_WIDTH = 0x80U};
    static const IData var_m_topsim__DOT__mmu__DOT__idbmem__DOT__cache__DOT__D_WIDTH;
    enum _IDatam_topsim__DOT__mmu__DOT__idbmem__DOT__cache__DOT__ENTRY { m_topsim__DOT__mmu__DOT__idbmem__DOT__cache__DOT__ENTRY = 0x2000U};
    static const IData var_m_topsim__DOT__mmu__DOT__idbmem__DOT__cache__DOT__ENTRY;
    enum _IDatam_topsim__DOT__mmu__DOT__idbmem__DOT__cache__DOT__mem__DOT__WIDTH { m_topsim__DOT__mmu__DOT__idbmem__DOT__cache__DOT__mem__DOT__WIDTH = 0x90U};
    static const IData var_m_topsim__DOT__mmu__DOT__idbmem__DOT__cache__DOT__mem__DOT__WIDTH;
    enum _IDatam_topsim__DOT__mmu__DOT__idbmem__DOT__cache__DOT__mem__DOT__ENTRY { m_topsim__DOT__mmu__DOT__idbmem__DOT__cache__DOT__mem__DOT__ENTRY = 0x2000U};
    static const IData var_m_topsim__DOT__mmu__DOT__idbmem__DOT__cache__DOT__mem__DOT__ENTRY;
    enum _IDatam_topsim__DOT__mmu__DOT__idbmem__DOT__idbmem__DOT__MEM_SIZE { m_topsim__DOT__mmu__DOT__idbmem__DOT__idbmem__DOT__MEM_SIZE = 0x8000000U};
    static const IData var_m_topsim__DOT__mmu__DOT__idbmem__DOT__idbmem__DOT__MEM_SIZE;
    
    // CONSTRUCTORS
  private:
    VL_UNCOPYABLE(Vm_topsim);  ///< Copying not allowed
  public:
    /// Construct the model; called by application code
    /// If contextp is null, then the model will use the default global context
    /// If name is "", then makes a wrapper with a
    /// single model invisible with respect to DPI scope names.
    Vm_topsim(VerilatedContext* contextp, const char* name = "TOP");
    Vm_topsim(const char* name = "TOP")
      : Vm_topsim(nullptr, name) {}
    /// Destroy the model; called (often implicitly) by application code
    ~Vm_topsim();
    
    // API METHODS
    /// Return current simulation context for this model.
    /// Used to get to e.g. simulation time via contextp()->time()
    VerilatedContext* contextp();
    /// Evaluate the model.  Application must call when inputs change.
    void eval() { eval_step(); }
    /// Evaluate when calling multiple units/models per time step.
    void eval_step();
    /// Evaluate at end of a timestep for tracing, when using eval_step().
    /// Application must call after all eval() and before time changes.
    void eval_end_step() {}
    /// Simulation complete, run final blocks.  Application must call on completion.
    void final();
    
    // INTERNAL METHODS
    static void _eval_initial_loop(Vm_topsim__Syms* __restrict vlSymsp);
    void __Vconfigure(Vm_topsim__Syms* symsp, bool first);
  private:
    static QData _change_request(Vm_topsim__Syms* __restrict vlSymsp);
    static QData _change_request_1(Vm_topsim__Syms* __restrict vlSymsp);
  public:
    static void _combo__TOP__5(Vm_topsim__Syms* __restrict vlSymsp);
  private:
    void _ctor_var_reset() VL_ATTR_COLD;
  public:
    static void _eval(Vm_topsim__Syms* __restrict vlSymsp);
  private:
#ifdef VL_DEBUG
    void _eval_debug_assertions();
#endif  // VL_DEBUG
  public:
    static void _eval_initial(Vm_topsim__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _eval_settle(Vm_topsim__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _initial__TOP__1(Vm_topsim__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _sequent__TOP__3(Vm_topsim__Syms* __restrict vlSymsp);
    static void _sequent__TOP__4(Vm_topsim__Syms* __restrict vlSymsp);
    static void _settle__TOP__2(Vm_topsim__Syms* __restrict vlSymsp) VL_ATTR_COLD;
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);

//----------


#endif  // guard
